editor: code -w
gitignore: false
analytics: false
light-mode: true
disable-playwright: true

# load API keys from ~/.aider.env
# TODO: implement support for ~ in aider
env-file: /home/mskrajnowski/.aider.env

model: gemini-2.5-pro
weak-model: gemini-2.5-flash
editor-model: gemini-2.5-flash

alias:
  # openai family
  - 4o:openrouter/openai/gpt-4o
  - 4o-mini:openrouter/openai/gpt-4o-mini
  - 4.1:openrouter/openai/gpt-4.1
  - 4.1-mini:openrouter/openai/gpt-4.1-mini
  - 4.1-nano:openrouter/openai/gpt-4.1-nano
  - o4-mini:openrouter/openai/o4-mini
  - o3-mini:openrouter/openai/o3-mini

  # gemini family
  - gemini-2.5-pro:openrouter/google/gemini-2.5-pro-preview
  - gemini-2.5-flash-thinking:openrouter/google/gemini-2.5-flash-preview-05-20:thinking
  - gemini-2.5-flash:openrouter/google/gemini-2.5-flash-preview-05-20
  - gemini-2.5-lite:openrouter/google/gemini-2.5-flash-lite-preview-06-17
  - gemini-2.0-flash:openrouter/google/gemini-2.0-flash-001
  - gemini-2.0-lite:openrouter/google/gemini-2.0-flash-lite-001

  # anthropic family
  - opus-4:openrouter/anthropic/claude-opus-4
  - opus-3:openrouter/anthropic/claude-opus-3
  - sonnet-4:openrouter/anthropic/claude-sonnet-4
  - sonnet-3.7:openrouter/anthropic/claude-3.7-sonnet
  - haiku-3.5:openrouter/anthropic/claude-3.5-haiku
  - haiku-3:openrouter/anthropic/claude-3-haiku

  # mistral family
  - devstral-small:openrouter/mistralai/devstral-small

  # deepseek family
  - deepseek-v3:openrouter/deepseek/deepseek-chat-v3-0324
  - deepseek-r1:openrouter/deepseek/deepseek-r1-0528
