#!/usr/bin/env bash

set -e

restore_path="$HOME/.yadm/dconf/restore"

echo '#!/usr/bin/env sh' > "$restore_path"
echo >> "$restore_path"
chmod +x "$restore_path"

function backup_key {
    schema=$1
    key=$2

    value=$(gsettings get $schema $key || echo "''")
    default=$(XDG_CONFIG_HOME=/none gsettings get $schema $key || echo "''")

    if [ "$value" != "$default" ]; then
        echo "gsettings set $schema $key \"$value\"" >> "$restore_path"
    fi
}

cat backed_keys.txt | sort | while read -r line; do
    backup_key $line
done
