#!/usr/bin/env bash

set -e

restore_path="$HOME/.yadm/vscode/restore"

echo '#!/usr/bin/env sh' > "$restore_path"
echo >> "$restore_path"
chmod +x "$restore_path"

code --list-extensions | sort --ignore-case | while read -r extension; do
    echo "code --install-extension \"$extension\"" >> "$restore_path"
done
